= Fuse on SpringBoot

*File InProgressRepo Quickstart*

:numbered:

== Overview
The Camel file component provides a link:https://camel.apache.org/components/3.15.x/eips/idempotentConsumer-eip.html#_idempotent_consumer_implementations[variety of options] for enabling it for a high-available environment. The purpose of this quickstart is to demonstrate the file component enabled with a variety of these external state management tools.



This project includes the following:

. Containerized state mgmt tools:
.. PostgreSQL database 
+
This database will maintain the HA management state of the file component used in the _jdbc-file-service_ quickstart.

. Fuse route with file component
+
This file component is enabled for HA by leveraging _JdbcOrphanLockAwareIdempotentRepository_

. Test results in both single and multi-node setup

. jdbc-file-service specific:  _JdbcOrphanLockAwareIdempotentRepository_ class
+
Back-ported to camel-2.23.2  (the version of camel leveraged in Fuse 2.10)

== Test

For any of the tests listed below, change into the directory specific to the type of _inProgressRepo_ of interest.

=== State Management Startup

For the purpose of facilitating testing, both a PostgreSQL and Redis are provided in this quickstart via _docker-compose.

To start them, execute the following:

-----
$ docker-compose -f etc/docker-compose.yaml up -d
-----

=== Single Node Tests

. Command-line:
+
-----
$ mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=8080 --com.redhat.test.processor.name=filetestservice"
-----

. Happy path test
.. File added
.. File component detects file
.. Graceful shutdown of JVM is initiated
.. JVM blocks
.. Route completes
.. File is successfully processed

. Orphan lock test with same processor

.. File is added; file component is shutdown via kill -9;
.. File remains and orphan lock exists in camel_messageprocessed db;
.. Restart JVM with same processor name;
.. Additional orphan lock added to database;
.. File successfully processed and both records deleted from camel_messageprocessed db

=== Multi Node Tests

. Command-line:
+
-----
$ mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=8080 --com.redhat.test.processor.name=filetestservice"
$ mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=8081 --com.redhat.test.processor.name=filetestservice"
-----

. Happy path test
.. File added
.. File component detects file
.. Graceful shutdown of JVM of file component that detected file is initiated
.. After about 5 minutes, file component of 2nd JVM processes file
.. Route completes
.. File is successfully processed


. Orphan lock test with different processor

.. Start both Fuse services
.. File is added; file component that initially processed the file is shutdown via kill -9 ;
.. File remains and orphan lock exists in camel_messageprocessed db;
.. Restart JVM with same processor name;
.. Additional orphan lock added to database;
.. File successfully processed and both records deleted from camel_messageprocessed db

== Redis cheatsheet

. Delete all lingering cache files:
+
-----
$ rm redis-file-service/cache/*.rdb
-----

. List all keys:
+
-----
$ podman exec -it redis /bin/sh
/data # redis-cli --pass admin
>  KEYS *

-----
