= Fuse on SpringBoot

*File InProgressRepo Quickstart*

:numbered:

== Overview
The Camel file component provides a link:https://camel.apache.org/components/3.15.x/eips/idempotentConsumer-eip.html#_idempotent_consumer_implementations[variety of options] for enabling it for a high-available environment. The purpose of this quickstart is to demonstrate the file component enabled with the JdbcOrphanLockAwareIdempotentRepository class.



This project includes the following:

. Containerized PostgreSQL database 
+
This database will maintain the HA management state of the file component used in this quickstart

. Fuse route with file component
+
This file component is enabled for HA by leveraging _JdbcOrphanLockAwareIdempotentRepository_

. _JdbcOrphanLockAwareIdempotentRepository_ class
+
Back-ported to camel-2.23.2  (leveraged in Fuse 2.10)

. Test results in both single and multi-node setup

== Testing

=== Single Node

. Command-line:
+
-----
$ mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=8080 --com.redhat.test.processor.name=filetestservice"
-----

. Happy path test
.. File added
.. File component detects file
.. Graceful shutdown of JVM is initiated
.. JVM blocks
.. Route completes
.. File is successfully processed

. Orphan lock test with same processor

.. File is added; file component is shutdown via kill -9;
.. File remains and orphan lock exists in camel_messageprocessed db;
.. Restart JVM with same processor name;
.. Additional orphan lock added to database;
.. File successfully processed and both records deleted from camel_messageprocessed db

=== Multi Node

. Command-line:
+
-----
$ mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=8080 --com.redhat.test.processor.name=filetestservice"
$ mvn spring-boot:run -Dspring-boot.run.arguments="--server.port=8081 --com.redhat.test.processor.name=filetestservice"
-----

. Happy path test
.. File added
.. File component detects file
.. Graceful shutdown of JVM of file component that detected file is initiated
.. After about 5 minutes, file component of 2nd JVM processes file
.. Route completes
.. File is successfully processed


. Orphan lock test with different processor

.. Start both Fuse services
.. File is added; file component that initially processed the file is shutdown via kill -9 ;
.. File remains and orphan lock exists in camel_messageprocessed db;
.. Restart JVM with same processor name;
.. Additional orphan lock added to database;
.. File successfully processed and both records deleted from camel_messageprocessed db

